version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  expressapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expressapp
    environment:
      MONGO_URL: mongodb://root:devpassword@mongo:27017/bookDB?authSource=admin
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/expressapp
    command: ["npm", "run", "start"]

volumes:
  mongo-data:
